{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $podMetadata := .Values.restapi.metadata | default dict -}}
{{- $labels := fromYaml (include "slurm.labels" $) -}}
{{- $podMetadata = merge (dict "labels" $labels) ($podMetadata | default dict) -}}
{{- $podSpec := .Values.restapi.podSpec | default dict -}}
{{- $imagePullSecrets := concat list ($podSpec.imagePullSecrets | default list) (.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podSpec "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podSpec.priorityClassName | default .Values.priorityClassName -}}
{{- $_ := set $podSpec "priorityClassName" $priorityClassName -}}
{{- $podTemplate := dict "metadata" $podMetadata "spec" $podSpec -}}
apiVersion: slinky.slurm.net/v1alpha1
kind: RestApi
metadata:
  name: {{ include "slurm.fullname" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  controllerRef:
    name: {{ include "slurm.fullname" . }}
    namespace: {{ include "slurm.namespace" . }}
  {{- with .Values.restapi.replicas }}
  replicas: {{ . }}
  {{- end }}{{- /* with .Values.restapi.replicas */}}
  slurmrestd:
    {{- include "format-container" .Values.restapi.slurmrestd | nindent 4 }}
  {{- include "format-podTemplate" $podTemplate | nindent 2 }}
  {{- with .Values.restapi.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with .Values.restapi.service */}}
