{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "slurm.controller.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.controller.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  revisionHistoryLimit: 0
  serviceName: {{ include "slurm.controller.name" . }}
  selector:
    matchLabels:
      {{- include "slurm.controller.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: slurmctld
      labels:
        {{- include "slurm.controller.labels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.controller.priorityClassName | default .Values.priorityClassName }}
      automountServiceAccountToken: false
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.controller.affinity */}}
      {{- include "slurm.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: init
          image: {{ include "slurm.authcred.imageRef" . }}
          imagePullPolicy: {{ .Values.authcred.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          {{- with .Values.authcred.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with .Values.authcred.resources */}}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" . }}
          command:
            - tini
            - -g
            - --
            - bash
            - -c
            - |
              {{- range .Files.Lines "scripts/init.sh" }}
              {{ . }}
              {{- end }}{{- /* range .Files.Lines "scripts/init.sh" */}}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" . | nindent 12 }}
            - name: {{ include "slurm.controller.statesave.name" . }}
              mountPath: {{ include "slurm.controller.statesavePath" . }}
      containers:
        - name: slurmctld
          image: {{ include "slurm.controller.imageRef" . }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          securityContext:
            {{- include "slurm.securityContext" . | nindent 12 }}
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with .Values.controller.resources */}}
          ports:
            - name: slurmctld
              containerPort: {{ include "slurm.controller.port" . }}
          readinessProbe:
            tcpSocket:
              port: slurmctld
          volumeMounts:
            {{- include "slurm.volumeMounts" . | nindent 12 }}
            - name: authsocket
              mountPath: /run/slurmctld
            - name: {{ include "slurm.controller.statesave.name" . }}
              mountPath: {{ include "slurm.controller.statesavePath" . }}
        - name: reconfigure
          image: {{ include "slurm.authcred.imageRef" . }}
          imagePullPolicy: {{ .Values.authcred.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          {{- with .Values.authcred.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with .Values.authcred.resources */}}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" . }}
          command:
            - tini
            - -g
            - --
            - bash
            - -c
            - |
              {{- range .Files.Lines "scripts/reconfigure.sh" }}
              {{ . }}
              {{- end }}{{- /* range .Files.Lines "scripts/reconfigure.sh" */}}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" . | nindent 12 }}
            - name: authsocket
              mountPath: /run/slurmctld
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.controller.tolerations */}}
      volumes:
        {{- include "slurm.volumes" . | nindent 8 }}
        - name: slurm-config
          projected:
            defaultMode: 0600
            sources:
              - configMap:
                  name: {{ include "slurm.configMapName" . }}
              - secret:
                  name: {{ include "slurm.auth.secretName" . }}
              - secret:
                  name: {{ include "slurm.jwt.hs256.secretName" . }}
        - name: authsocket
          emptyDir: {}
        {{- if and .Values.controller.persistence.enabled .Values.controller.persistence.existingClaim }}
        - name: {{ include "slurm.controller.statesave.name" . }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.controller.persistence.existingClaim . }}
        {{- else if not .Values.controller.persistence.enabled }}
        - name: {{ include "slurm.controller.statesave.name" . }}
          emptyDir: {}
        {{- end }}{{- /* if and .Values.controller.persistence.enabled .Values.controller.persistence.existingClaim */}}
  {{- if and .Values.controller.persistence.enabled (not .Values.controller.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "slurm.controller.statesave.name" . }}
        namespace: {{ include "slurm.namespace" . }}
        {{- with .Values.controller.persistence.annotations }}
        annotations:
          {{- toYaml . | indent 10 }}
        {{- end }}{{- /* with .Values.controller.persistence.annotations */}}
        labels:
          {{- include "slurm.controller.labels" . | nindent 10 }}
          {{- with .Values.controller.persistence.labels }}
          {{- toYaml . | indent 10 }}
          {{- end }}{{- /* with .Values.controller.persistence.labels */}}
      spec:
        accessModes:
          {{- range .Values.controller.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.controller.persistence.size | quote }}
        storageClassName: {{ .Values.controller.persistence.storageClass | quote }}
        {{- with .Values.controller.persistence.selector }}
        selector:
          {{- toYaml . | indent 10 }}
        {{- end -}}{{- /* with .Values.controller.persistence.selector */}}
  {{- end -}}{{- /* if and .Values.persistence.enabled (not .Values.controller.persistence.existingClaim) */}}
