{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- range $key, $nodeset := $.Values.nodesets -}}
{{- if $nodeset.enabled }}
{{- $name := printf "%s-%s" (include "slurm.worker.name" $) $key }}
{{- $podMetadata := $nodeset.metadata | default dict -}}
{{- $labels := fromYaml (include "slurm.labels" $) -}}
{{- $labels = merge $labels (dict "nodeset.slinky.slurm.net/name" $name) -}}
{{- $podMetadata = merge (dict "labels" $labels) ($podMetadata | default dict) -}}
{{- $podSpec := $nodeset.podSpec | default dict -}}
{{- $imagePullSecrets := concat list ($podSpec.imagePullSecrets | default list) ($.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podSpec "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podSpec.priorityClassName | default $.Values.priorityClassName -}}
{{- $_ := set $podSpec "priorityClassName" $priorityClassName -}}
{{- $_ := set $podSpec "hostname" (printf "%s-" $key) -}}
{{- $podTemplate := dict "metadata" $podMetadata "spec" $podSpec -}}
{{- if $nodeset.useResourceLimits }}
  {{- $envLimts := list (dict "name" "POD_CPUS" "value" (include "slurm.worker.podCpus" $nodeset.slurmd | toString)) (dict "name" "POD_MEMORY" "value" (include "slurm.worker.podMemory" $nodeset.slurmd | toString)) -}}
  {{- $slurmdEnv := concat list ($nodeset.slurmd.env | default list) $envLimts -}}
  {{- $_ := set $nodeset.slurmd "env" $slurmdEnv -}}
{{- end }}{{- /* if $nodeset.useResourceLimits */}}
{{- if and (include "vendor.dcgm.enabled" $) (include "vendor.dcgm.nodesetHasGPU" $nodeset.slurmd) }}
  {{- $volumeMounts := $nodeset.slurmd.volumeMounts | default list -}}
  {{- $dcgmVolumeMount := dict "name" "dcgm-job-mapping" "mountPath" (include "vendor.dcgm.jobMappingDir" $) }}
  {{- $volumeMounts = append $volumeMounts $dcgmVolumeMount }}
  {{- $_ := set $nodeset.slurmd "volumeMounts" $volumeMounts -}}
  {{- $volumes := $nodeset.podSpec.volumes | default list -}}
  {{- $dcgmVolume := dict "name" "dcgm-job-mapping" "hostPath" (dict "path" (include "vendor.dcgm.jobMappingDir" $) "type" "DirectoryOrCreate") }}
  {{- $volumes = append $volumes $dcgmVolume }}
  {{- $_ := set $nodeset.podSpec "volumes" $volumes -}}
{{- end }}
---
apiVersion: slinky.slurm.net/v1alpha1
kind: NodeSet
metadata:
  name: {{ $name }}
  namespace: {{ include "slurm.namespace" $ }}
  labels:
    nodeset.slinky.slurm.net/name: {{ $name }}
    {{- include "slurm.labels" $ | nindent 4 }}
spec:
  controllerRef:
    name: {{ include "slurm.fullname" $ }}
    namespace: {{ include "slurm.namespace" $ }}
  {{- if (include "slurm.worker.extraConf" $nodeset) }}
  extraConf: {{ include "slurm.worker.extraConf" $nodeset }}
  {{- end -}}{{- /* if (include "slurm.worker.extraConf" $nodeset) */}}
  {{- with $nodeset.partition }}
  partition:
    enabled: {{ $nodeset.partition.enabled | default false }}
    {{- if (include "slurm.worker.partitionConfig" $nodeset.partition) }}
    config: {{ include "slurm.worker.partitionConfig" $nodeset.partition }}
    {{- end }}{{- /* if (include "slurm.worker.partitionConfig" $nodeset.partition) */}}
  {{- end }}{{- /* with $nodeset.partition */}}
  replicas: {{ $nodeset.replicas }}
  slurmd:
    {{- $_ := set $nodeset.slurmd "imagePullPolicy" (default $.Values.imagePullPolicy $nodeset.slurmd.imagePullPolicy) -}}
    {{- include "format-container" $nodeset.slurmd | nindent 4 }}
  logfile:
    {{- $_ := set $nodeset.logfile "imagePullPolicy" (default $.Values.imagePullPolicy $nodeset.logfile.imagePullPolicy) -}}
    {{- include "format-container" $nodeset.logfile | nindent 4 }}
  {{- include "format-podTemplate" $podTemplate | nindent 2 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
{{- end }}{{- /* $nodeset.enabled */}}
{{- end }}{{- /* range $nodeset := $.Values.nodesets */}}
