{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.webhook.enabled .Values.webhook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slurm-operator.webhook.serviceAccountName" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "slurm-operator.webhook.name" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ include "slurm-operator.apiGroup" . }}
  resources:
  - accountings
  - controllers
  - loginsets
  - nodesets
  - restapis
  - tokens
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "slurm-operator.webhook.serviceAccountName" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "slurm-operator.webhook.serviceAccountName" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "slurm-operator.webhook.serviceAccountName" . }}
{{- end }}{{- /* if and .Values.webhook.enabled .Values.webhook.serviceAccount.create */}}
