---
apiVersion: v2

name: slurm-operator-crds
description: Slurm Operator CRDs
type: application
version: 0.4.0

annotations:
  license: Apache-2.0

home: https://slinky.schedmd.com/
icon: https://github.com/SlinkyProject/docs/blob/main/docs/_static/images/slinky.svg

sources:
  - https://github.com/SlinkyProject/slurm-operator

maintainers:
  - name: SchedMD LLC.
    email: slinky@schedmd.com
    url: https://support.schedmd.com/
