{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $secretName := (include "slurm.jwt.hs256.secretName" .) -}}
{{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- if not .Values.jwt.hs256.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    app.kubernetes.io/component: auth
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if or .Release.IsInstall (empty ($secret).data) }}
  jwt_hs256.key: {{ randAscii 32 | b64enc | quote }}
  {{- else }}{{- /* if or .Release.IsInstall (empty ($secret).data) */}}
  jwt_hs256.key: {{ index ($secret).data "jwt_hs256.key" }}
  {{- end }}{{- /* if or .Release.IsInstall (empty ($secret).data) */}}
{{- end }}{{- /* if not .Values.jwt.hs256.existingSecret */}}
