{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.accounting.enabled .Values.accounting.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slurm.accounting.secretName" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.accounting.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ print .Values.accounting.external.password | b64enc | quote }}
{{- end }}{{- /* if and .Values.accounting.enabled .Values.accounting.external.enabled */}}
