{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.accounting.enabled }}
{{- if and (not .Values.accounting.external.enabled) (not .Values.mariadb.enabled) }}
  {{- fail "Incompatible configuration: `accounting.enabled=true`; `accounting.external.enabled=false`; `mariadb.enabled=false`. Either set `accounting.enabled=false`, `accounting.external.enabled=true`, or `mariadb.enabled=true`." }}
{{- end }}{{- /* if and (not .Values.accounting.external.enabled) (not .Values.mariadb.enabled) */}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "slurm.accounting.name" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.accounting.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  revisionHistoryLimit: 0
  serviceName: {{ include "slurm.accounting.name" . }}
  selector:
    matchLabels:
      {{- include "slurm.accounting.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: slurmdbd
      labels:
        {{- include "slurm.accounting.labels" . | nindent 8 }}
    spec:
      hostname: {{ include "slurm.accounting.name" . }}
      priorityClassName: {{ .Values.accounting.priorityClassName | default .Values.priorityClassName }}
      automountServiceAccountToken: false
      {{- with .Values.accounting.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.accounting.affinity */}}
      {{- include "slurm.imagePullSecrets" $ | nindent 6 }}
      initContainers:
        - name: init
          image: {{ include "slurm.authcred.imageRef" . }}
          imagePullPolicy: {{ .Values.authcred.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          {{- with .Values.authcred.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with .Values.authcred.resources */}}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" . }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" .Subcharts.mariadb }}
                  key: mariadb-password
          command:
            - tini
            - -g
            - --
            - bash
            - -c
            - |
              {{- range .Files.Lines "scripts/init.sh" }}
              {{ . }}
              {{- end }}{{- /* range .Files.Lines "scripts/init.sh" */}}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" . | nindent 12 }}
      containers:
        - name: slurmdbd
          image: {{ include "slurm.accounting.imageRef" . }}
          imagePullPolicy: {{ .Values.accounting.imagePullPolicy | default (include "slurm.imagePullPolicy" .) }}
          securityContext:
            {{- include "slurm.securityContext" . | nindent 12 }}
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with .Values.controller.resources */}}
          ports:
            - name: slurmdbd
              containerPort: {{ include "slurm.accounting.port" . }}
          readinessProbe:
            tcpSocket:
              port: slurmdbd
          volumeMounts:
            {{- include "slurm.volumeMounts" . | nindent 12 }}
      {{- with .Values.accounting.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with .Values.accounting.tolerations */}}
      volumes:
        {{- include "slurm.volumes" . | nindent 8 }}
        - name: slurm-config
          projected:
            defaultMode: 0600
            sources:
              - configMap:
                  name: {{ include "slurm.accounting.config.name" . }}
              - secret:
                  name: {{ include "slurm.auth.secretName" . }}
              - secret:
                  name: {{ include "slurm.jwt.hs256.secretName" . }}
{{- end }}{{- /* if .Values.accounting.enabled */}}
