# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

# -- Overrides the name of the release.
nameOverride: ""

# -- Overrides the full name of the release.
fullnameOverride: ""

# -- Overrides the namespace of the release.
namespaceOverride: ""

# -- Sets the image pull secrets.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
  # - name: regcred

# -- Set the priority class to use.
# Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass
priorityClassName: ""

# Operator configurations.
operator:
  # -- Enables the operator.
  enabled: true
  # -- Set the number of replicas to deploy.
  replicas: 1
  # -- Set the image pull policy.
  imagePullPolicy: IfNotPresent
  # The image to use, `${repository}:${tag}`.
  # Ref: https://kubernetes.io/docs/concepts/containers/images/#image-names
  image:
    repository: ghcr.io/slinkyproject/slurm-operator
    tag: ""
  # Service account configurations.
  serviceAccount:
    # -- Allows chart to create the service account.
    create: true
    # -- Set the service account to use (and create).
    name: ""
  # -- Affinity for pod assignment.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  # -- Tolerations for pod assignment.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
    # - key: key1
    #   operator: Exists
    #   effect: NoSchedule
  # -- The container resource limits and requests.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  # -- Set the max concurrent workers for the Cluster controller.
  clusterWorkers: 1
  # -- Set the max concurrent workers for the NodeSet controller.
  nodesetWorkers: 1
  # -- Set the log level by string (e.g. error, info, debug) or number (e.g. 1..5).
  logLevel: info

# Webhook configurations.
webhook:
  # -- Enable the webhook.
  enabled: true
  # -- Set the number of replicas to deploy.
  replicas: 1
  # -- Set the image pull policy.
  imagePullPolicy: IfNotPresent
  # The image to use, `${repository}:${tag}`.
  # Ref: https://kubernetes.io/docs/concepts/containers/images/#image-names
  image:
    repository: ghcr.io/slinkyproject/slurm-operator-webhook
    tag: ""
  #
  # Service account configurations.
  serviceAccount:
    # -- Allows chart to create the service account.
    create: true
    # -- Set the service account to use (and create).
    name: ""
  # -- Set the timeout period for calls.
  timeoutSeconds: 10
  # -- Affinity for pod assignment.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  # -- Tolerations for pod assignment.
  # Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations: []
    # - key: key1
    #   operator: Exists
    #   effect: NoSchedule
  # -- The container resource limits and requests.
  # Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
  resources: {}
    # requests:
    #   cpu: 1
    #   memory: 1Gi
    # limits:
    #   cpu: 2
    #   memory: 4Gi
  # -- Set the log level by string (e.g. error, info, debug) or number (e.g. 1..5).
  logLevel: info

#
# Cert-Manager certificate configurations.
certManager:
  # -- Enable cert-manager for certificate management.
  enabled: true
  # -- The secret to be (created and) mounted.
  secretName: slurm-operator-webhook-ca
  # -- Duration of certificate life.
  duration: 43800h0m0s # 5 year
  # -- Certificate renewal time. Should be before the expiration.
  renewBefore: 8760h0m0s # 1 year
