## Append samples of your project ##
resources:
- slinky_v1alpha1_accounting.yaml
- slinky_v1alpha1_controller.yaml
- slinky_v1alpha1_loginset.yaml
- slinky_v1alpha1_nodeset.yaml
- slinky_v1alpha1_restapi.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
