apiVersion: slinky.slurm.net/v1alpha1
kind: Accounting
metadata:
  labels:
    app.kubernetes.io/name: nodeset
    app.kubernetes.io/instance: nodeset-sample
    app.kubernetes.io/part-of: slurm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: slurm-operator
  name: nodeset-sample
spec:
  # TODO(user): Add fields here
