{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- range $nodeset := .Values.compute.nodesets -}}
{{- if $nodeset.enabled }}
{{- $repository := $nodeset.image.repository | default (include "slurm.compute.image.repository" $) }}
{{- $tag := $nodeset.image.tag | default (include "slurm.compute.image.tag" $) }}
{{- $imageRef := printf "%s:%s" $repository $tag }}
{{- $name := printf "%s-%s" (include "slurm.compute.name" $) $nodeset.name }}
{{- $authcredRepository := include "slurm.authcred.image.repository" $ }}
{{- $authcredTag := include "slurm.authcred.image.repository" $ }}
{{- $authcredImagePullPolicy := $nodeset.imagePullPolicy | default (include "slurm.imagePullPolicy" $) }}
{{- $authcredResources := $.Values.authcred.resources }}
{{- with $nodeset.authcred -}}
  {{- with .image -}}
    {{- $authcredRepository = .repository | default $authcredRepository -}}
    {{- $authcredTag = .tag | default $authcredTag -}}
  {{- end -}}
  {{- $authcredImagePullPolicy = .imagePullPolicy | default $authcredImagePullPolicy -}}
  {{- $authcredResources = .resources | default $authcredResources -}}
{{- end -}}
{{- $authcredImageRef := printf "%s:%s" $authcredRepository $authcredTag }}
---
apiVersion: slinky.slurm.net/v1alpha1
kind: NodeSet
metadata:
  name: {{ $name }}
  namespace: {{ include "slurm.namespace" $ }}
  labels:
    nodeset.slinky.slurm.net/name: {{ $name }}
    {{- include "slurm.compute.labels" $ | nindent 4 }}
spec:
  clusterName: {{ include "slurm.cluster.name" $ }}
  replicas: {{ $nodeset.replicas }}
  serviceName: {{ include "slurm.compute.name" $ }}
  {{- with $nodeset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with $nodeset.updateStrategy */}}
  {{- with $nodeset.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with $nodeset.persistentVolumeClaimRetentionPolicy */}}
  selector:
    matchLabels:
      nodeset.slinky.slurm.net/name: {{ $name }}
      {{- include "slurm.compute.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: slurmd
      labels:
        nodeset.slinky.slurm.net/name: {{ $name }}
        {{- include "slurm.compute.labels" $ | nindent 8 }}
    spec:
      hostname: "{{ $nodeset.name }}-"
      priorityClassName: {{ $nodeset.priorityClassName | default $.Values.priorityClassName }}
      automountServiceAccountToken: false
      dnsConfig:
        {{- include "slurm.dnsConfig" $ | nindent 8 }}
      {{- include "slurm.imagePullSecrets" $ | nindent 6 }}
      initContainers:
        - name: init
          image: {{ $authcredImageRef }}
          imagePullPolicy: {{ $authcredImagePullPolicy }}
          {{- with $authcredResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with $authcredResources */}}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" $ }}
          command:
            - tini
            - -g
            - --
            - bash
            - -c
            - |
              {{- range $.Files.Lines "scripts/init.sh" }}
              {{ . }}
              {{- end }}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" $ | nindent 12 }}
        - name: logfile
          image: {{ $authcredImageRef }}
          imagePullPolicy: {{ $authcredImagePullPolicy }}
          restartPolicy: Always
          env:
            - name: SOCKET
              value: {{ include "slurm.compute.logFile" $ }}
          command:
            - tini
            - -g
            - --
            - bash
            - -c
            - |
              {{- range $.Files.Lines "scripts/socket-logger.sh" }}
              {{ . }}
              {{- end }}{{- /* range $.Files.Lines "scripts/socket-logger.sh" */}}
          {{- with $authcredResources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with $authcredResources */}}
          volumeMounts:
            - name: slurm-log
              mountPath: /var/log/slurm
      containers:
        - name: slurmd
          image: {{ $imageRef }}
          securityContext:
            privileged: true
            capabilities:
              add:
                {{- include "slurm.compute.capabilities" $ | nindent 16 }}
          imagePullPolicy: {{ $nodeset.imagePullPolicy | default (include "slurm.imagePullPolicy" $) }}
          {{- with $nodeset.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}{{- /* with $nodeset.resources */}}
          {{- if $nodeset.useResourceLimits }}
          env:
            - name: POD_CPUS
              value: {{ include "slurm.compute.podCpus" $nodeset | toString | quote }}
            - name: POD_MEMORY
              value: {{ include "slurm.compute.podMemory" $nodeset | toString | quote }}
          {{- end }}{{- /* if $nodeset.useResourceLimits */}}
          args:
            - -Z
            - --conf-server
            - {{ printf "%s:%s" (include "slurm.controller.name" $) (include "slurm.controller.port" $) }}
            - --conf
            - {{ include "slurm.compute.conf" $nodeset }}
          ports:
            - name: slurmd
              containerPort: {{ include "slurm.compute.port" $ }}
          readinessProbe:
            tcpSocket:
              port: slurmd
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - >-
                    scontrol update nodename=$(hostname) state=down reason=preStop &&
                    scontrol delete nodename=$(hostname);
          volumeMounts:
            {{- include "slurm.volumeMounts" $ | nindent 12 }}
            - name: slurm-spool
              mountPath: {{ include "slurm.compute.spoolDir" . }}
            - name: slurm-log
              mountPath: /var/log/slurm
            {{- range $vct := $nodeset.volumeClaimTemplates }}
            - name: {{ $vct.metadata.name }}
              mountPath: {{ $vct.spec.mountPath | default (printf "/mnt/%s" $vct.metadata.name ) }}
            {{- end }}{{- /* range $vct := $nodeset.volumeClaimTemplates */}}
            {{- with $nodeset.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}{{- /* with $nodeset.extraVolumeMounts */}}
      {{- with $nodeset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with $nodeset.nodeSelector */}}
      {{- with $nodeset.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with $nodeset.affinity */}}
      {{- with $nodeset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}{{- /* with $nodeset.tolerations */}}
      volumes:
        {{- include "slurm.volumes" $ | nindent 8 }}
        - name: slurm-config
          projected:
            defaultMode: 0600
            sources:
              - secret:
                  name: {{ include "slurm.auth.secretName" $ }}
        - name: slurm-spool
          emptyDir:
            medium: Memory
        - name: slurm-log
          emptyDir:
            medium: Memory
        {{- with $nodeset.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}{{- /* with $nodeset.extraVolumes */}}
  {{- with $nodeset.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml (omit . "mountPath") | nindent 4 }}
  {{- end }}{{- /* with $nodeset.volumeClaimTemplates */}}
{{- end }}{{- /* if $nodeset.enabled */}}
{{- end }}{{- /* range $nodeset := .Values.compute.nodesets */}}
