{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- range $nodeset := .Values.compute.nodesets -}}
{{- if $nodeset.enabled }}
{{- if not $.Values.controller.enabled }}
  {{- fail "Slurm compute nodeset requires `controller.enabled=true`." -}}
{{- end }}{{- /* if not $.Values.controller.enabled */}}
{{- $repository := $nodeset.image.repository | default (include "slurm.compute.image.repository" $) }}
{{- $tag := $nodeset.image.tag | default (include "slurm.compute.image.tag" $) }}
{{- $imageRef := printf "%s:%s" $repository $tag }}
{{- $name := printf "%s-%s" (include "slurm.compute.name" $) $nodeset.name }}
---
apiVersion: slinky.slurm.net/v1alpha1
kind: NodeSet
metadata:
  name: {{ $name }}
  namespace: {{ include "slurm.namespace" $ }}
  labels:
    app.kubernetes.io/name: slurmd
    app.kubernetes.io/instance: {{ $name }}
    app.kubernetes.io/component: compute
    {{- include "slurm.labels" $ | nindent 4 }}
spec:
  clusterName: {{ include "slurm.cluster.name" $ }}
  replicas: {{ $nodeset.replicas }}
  serviceName: {{ include "slurm.compute.name" $ }}
  minReadySeconds: {{ $nodeset.minReadySeconds | default 0 }}
  {{- if $nodeset.updateStrategy }}
  updateStrategy:
    {{- $nodeset.updateStrategy | toYaml | nindent 4 }}
  {{- end }}{{- /* if $nodeset.updateStrategy */}}
  {{- if $nodeset.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    {{- $nodeset.persistentVolumeClaimRetentionPolicy | toYaml | nindent 4 }}
  {{- end }}{{- /* if $nodeset.persistentVolumeClaimRetentionPolicy */}}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $name }}
      {{- include "slurm.compute.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: slurmd
      labels:
        app.kubernetes.io/instance: {{ $name }}
        {{- include "slurm.compute.labels" $ | nindent 8 }}
    spec:
      hostname: {{ $name }}
      priorityClassName: {{ $nodeset.priorityClassName | default $.Values.priorityClassName }}
      automountServiceAccountToken: false
      dnsConfig:
        {{- include "slurm.dnsConfig" $ | nindent 8 }}
      {{- if $nodeset.nodeSelector }}
      nodeSelector:
        {{- $nodeset.nodeSelector | toYaml | nindent 8 }}
      {{- end }}{{- /* if $nodeset.nodeSelector */}}
      {{- if $nodeset.affinity }}
      affinity:
        {{- $nodeset.affinity | toYaml | nindent 8 }}
      {{- end }}{{- /* if $nodeset.affinity */}}
      {{- include "slurm.imagePullSecrets" $ | nindent 6 }}
      initContainers:
        - name: init
          image: {{ $imageRef }}
          imagePullPolicy: {{ $nodeset.imagePullPolicy | default (include "slurm.imagePullPolicy" $) }}
          env:
            - name: SLURM_USER
              value: {{ include "slurm.user" $ }}
          command:
            - bash
            - -c
            - |
              {{- range $.Files.Lines "scripts/init.sh" }}
              {{ . }}
              {{- end }}
          volumeMounts:
            {{- include "slurm.init.volumeMounts" $ | nindent 12 }}
      containers:
        - name: slurmd
          image: {{ $imageRef }}
          securityContext:
            privileged: true
            capabilities:
              add:
                {{- include "slurm.compute.capabilities" $ | nindent 16 }}
          imagePullPolicy: {{ $nodeset.imagePullPolicy | default (include "slurm.imagePullPolicy" $) }}
          {{- if not $nodeset.resources }}
            {{- fail "Slurm compute nodes require resources spec." -}}
          {{- else }}{{- /* if not $nodeset.resources */}}
          resources:
            {{- $nodeset.resources | toYaml | nindent 12 }}
          {{- end }}{{- /* if not $nodeset.resources */}}
          args:
            - -D
            - -Z
            - --conf-server
            - {{ printf "%s:%s" (include "slurm.controller.name" $) (include "slurm.controller.port" $) }}
            - --conf
            - >-
              Features={{- join "," (prepend (default (list) $nodeset.nodeFeatures) $nodeset.name) }}
              {{- if $nodeset.nodeGres }}
              Gres={{- $nodeset.nodeGres }}
              {{- end }}
              Weight={{- default 1 $nodeset.nodeWeight }}
          ports:
            - name: slurmd
              containerPort: {{ include "slurm.compute.port" $ }}
          startupProbe:
            exec:
              command:
                - scontrol
                - show
                - slurmd
          readinessProbe:
            exec:
              command:
                - scontrol
                - show
                - slurmd
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - >-
                    scontrol update nodename=$(hostname) state=down reason=preStop &&
                    scontrol delete nodename=$(hostname);
          volumeMounts:
            {{- include "slurm.volumeMounts" $ | nindent 12 }}
            {{- range $vct := $nodeset.volumeClaimTemplates }}
            - name: {{ $vct.metadata.name }}
              mountPath: {{ $vct.spec.mountPath | default (printf "/mnt/%s" $vct.metadata.name ) }}
            {{- end }}{{- /* range $vct := $nodeset.volumeClaimTemplates */}}
      volumes:
        {{- include "slurm.volumes" $ | nindent 8 }}
        - name: slurm-config
          projected:
            defaultMode: 0600
            sources:
              - secret:
                  name: {{ include "slurm.auth.secretName" $ }}
  {{- if $nodeset.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- $nodeset.volumeClaimTemplates | toYaml | nindent 4 }}
  {{- end }}{{- /* if $nodeset.volumeClaimTemplates */}}
{{- end }}{{- /* if $nodeset.enabled */}}
{{- end }}{{- /* range $nodeset := .Values.compute.nodesets */}}
