{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- range $key, $loginset := $.Values.loginsets -}}
{{- if $loginset.enabled }}
{{- $name := printf "%s-%s" (include "slurm.login.name" $) $key }}
{{- $podMetadata := $loginset.metadata | default dict -}}
{{- $labels := fromYaml (include "slurm.labels" $) -}}
{{- $labels = merge $labels (dict "loginset.slinky.slurm.net/name" $name) -}}
{{- $podMetadata = merge (dict "labels" $labels) ($podMetadata | default dict) -}}
{{- $podSpec := $loginset.podSpec | default dict -}}
{{- $imagePullSecrets := concat list ($podSpec.imagePullSecrets | default list) ($.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podSpec "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podSpec.priorityClassName | default $.Values.priorityClassName -}}
{{- $_ := set $podSpec "priorityClassName" $priorityClassName -}}
{{- $podTemplate := dict "metadata" $podMetadata "spec" $podSpec -}}
---
apiVersion: slinky.slurm.net/v1alpha1
kind: LoginSet
metadata:
  name: {{ $name }}
  namespace: {{ include "slurm.namespace" $ }}
  labels:
    loginset.slinky.slurm.net/name: {{ $name }}
    {{- include "slurm.labels" $ | nindent 4 }}
spec:
  controllerRef:
    name: {{ include "slurm.fullname" $ }}
    namespace: {{ include "slurm.namespace" $ }}
  {{- with $loginset.extraSshdConfig }}
  extraSshdConfig: |
    {{- . | nindent 4 }}
  {{- end }}{{- /* with $loginset.extraSshdConfig */}}
  sssdConfRef:
    name: {{ $name }}-sssd-conf
    key: sssd.conf
  {{- with $loginset.rootSshAuthorizedKeys }}
  rootSshAuthorizedKeys: |
    {{- . | nindent 4 }}
  {{- end }}{{- /* with $loginset.rootSshAuthorizedKeys */}}
  replicas: {{ $loginset.replicas }}
  login:
    {{- $_ := set $loginset.login "imagePullPolicy" (default $.Values.imagePullPolicy $loginset.login.imagePullPolicy) -}}
    {{- include "format-container" $loginset.login | nindent 4 }}
  {{- include "format-podTemplate" $podTemplate | nindent 2 }}
  {{- with $loginset.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with $loginset.service */}}
{{- end }}{{- /* $loginset.enabled */}}
{{- end }}{{- /* range $loginset := $.Values.loginsets */}}
